import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class Deposito extends javax.swing.JFrame {
    
    int TC, TCs,verificador;
    char accion;
    String nom;
    Float scorr,sahorr;
    long deposito;
    long dpd;
    
    
    public Deposito(int t,String c,Float scor, Float sahor, long dpds) {
        super("Simulador Cajero Automatico");
        this.sahorr=sahor;
        this.scorr=scor;
        this.TC=t;
        this.TCs=0;
        this.nom=c;
        this.deposito=1;
        this.dpd=dpds;
        
        System.out.println("tc dep: "+String.valueOf(TC));
        System.out.println("nom dep: "+String.valueOf(nom));
        System.out.println("ahorro dep: "+String.valueOf(sahorr));
        System.out.println("corr dep: "+String.valueOf(scorr));
        
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
        initComponents();
        this.jLNom.setText(nom);
                         
        
        if (TC==2)
        {
        jCahorro.setEnabled(false);
        jCcorriente.setSelected(true);
        this.jLsaldo.setText(String.valueOf(scorr));
        }
        
         if (TC==1)
        {
        jCcorriente.setEnabled(false);
        jCahorro.setSelected(true);
        this.jLsaldo.setText(String.valueOf(sahorr));
        }
        
         
         
        buttonGroup1.add(jCahorro);
        buttonGroup1.add(jCcorriente);
        
        java.util.Date utilDate = new java.util.Date(); //fecha actual
        long lnMilisegundos = utilDate.getTime();
        java.sql.Date sqlDate = new java.sql.Date(lnMilisegundos);
        java.sql.Time sqlTime = new java.sql.Time(lnMilisegundos);  //retorna la hora
        this.jLfecha.setText(sqlDate+"");   
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLNom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTdinero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLsaldo = new javax.swing.JLabel();
        jBaceptar = new javax.swing.JButton();
        jBvolver = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLfecha = new javax.swing.JLabel();
        jCahorro = new javax.swing.JCheckBox();
        jCcorriente = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24));
        jLabel1.setText("Banco del Pichincha");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 18));
        jLabel2.setText("Cliente:");

        jLNom.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLNom.setText(null);

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 18));
        jLabel4.setText("<< Deposito >>");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ingrese la Cantidad.-");
        jLabel5.setToolTipText("");

        jTdinero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTdinero.setText("<ingrese su dinero>");
        jTdinero.setToolTipText("");
        jTdinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTdineroMouseClicked(evt);
            }
        });
        jTdinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdineroActionPerformed(evt);
            }
        });
        jTdinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTdineroKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Saldo Actual.-");

        jLsaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLsaldo.setText("00000");

        jBaceptar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jBaceptar.setText("Aceptar");
        jBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarActionPerformed(evt);
            }
        });

        jBvolver.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jBvolver.setText("Volver");
        jBvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverActionPerformed(evt);
            }
        });

        jBcancelar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Fecha:");

        jLfecha.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLfecha.setText("2010/14/02   12:60");

        jCahorro.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jCahorro.setText("  Ahorros");
        jCahorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCahorroActionPerformed(evt);
            }
        });

        jCcorriente.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jCcorriente.setText("Corriente");
        jCcorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcorrienteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Seleccione la Cuenta:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Ingrese la Cantidad");

        salida.setFont(new java.awt.Font("Tahoma", 0, 14));
        salida.setText("00000");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Saldo Actualizado.-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salida)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLsaldo)
                                            .addComponent(jTdinero, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCahorro)
                                            .addComponent(jCcorriente))
                                        .addGap(29, 29, 29))
                                    .addComponent(jLabel8))
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jBaceptar)
                                .addGap(18, 18, 18)
                                .addComponent(jBvolver)
                                .addGap(18, 18, 18)
                                .addComponent(jBcancelar)
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLfecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLNom, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLNom))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCahorro))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLsaldo)
                    .addComponent(jCcorriente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salida)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancelar)
                    .addComponent(jBvolver)
                    .addComponent(jBaceptar))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLfecha)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverActionPerformed
        Opciones o=new Opciones(TC, nom, scorr,sahorr,dpd);
        setVisible(false);
        o.setVisible(true);
    }//GEN-LAST:event_jBvolverActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        Inicio a=new Inicio("Simulador Cajero Automatico");
        setVisible(false);        
        a.setVisible(true);
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTdineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdineroActionPerformed
        
    }//GEN-LAST:event_jTdineroActionPerformed

    private void jBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarActionPerformed
        
        if((verificador==1) || (TC==1))
        {
            TCs=1;
        }
        
        if((verificador==2) || (TC==2))
        {
            TCs=2;
        }
        
        if(jTdinero.getText().equalsIgnoreCase("<ingrese su dinero>") || jTdinero.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Ingrese su Dinero","Error",JOptionPane.ERROR_MESSAGE);
        }else {
            
        
        if((TCs==1) || (TCs==2))
        {
        try{
        Float.parseFloat(jTdinero.getText());

        try{
            this.deposito=Long.parseLong(jTdinero.getText());
            if(deposito<5)
            {
               JOptionPane.showMessageDialog(null, "Solo puede Depositar Cantidades Mayores a US$ 5","Error",JOptionPane.ERROR_MESSAGE);
            }
            else {
                accion='d';
                if(TCs==0)
                    {
                        TCs=TC;
                    }  
                
                Factura f=new Factura(TC, nom, scorr,sahorr,deposito,accion,TCs,dpd);
                setVisible(false);
                f.setVisible(true);
                }
        }
        catch(Exception err)
        {
            JOptionPane.showMessageDialog(null, "No se Puede Ingresar Monedas","Error",JOptionPane.ERROR_MESSAGE);
            jTdinero.setText("");
        }
        
        }catch(Exception err)
            {
                JOptionPane.showMessageDialog(null, "No Ingrese Billetes Extranjeros","Error",JOptionPane.ERROR_MESSAGE);
                jTdinero.setText("");
            }
        } else{
            JOptionPane.showMessageDialog(null, "Seleccione una Cuenta","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jBaceptarActionPerformed

    private void jCahorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCahorroActionPerformed
        this.jLsaldo.setText(String.valueOf(sahorr));
        verificador=1;
        
        try{
        Long a=Long.parseLong(jTdinero.getText());
        salida.setText(String.valueOf(sahorr+a));
        }
        catch(Exception err)
        {
            salida.setText("<Desconocido>");
        }
    }//GEN-LAST:event_jCahorroActionPerformed

    private void jCcorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcorrienteActionPerformed
        this.jLsaldo.setText(String.valueOf(scorr));
        verificador=2;
        
        try{
        Long a=Long.parseLong(jTdinero.getText());
        salida.setText(String.valueOf(scorr+a));
        }
        catch(Exception err)
        {
            salida.setText("<Desconocido>");
        }
    }//GEN-LAST:event_jCcorrienteActionPerformed

    private void jTdineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTdineroMouseClicked
        if(jTdinero.getText().equalsIgnoreCase("<ingrese su dinero>"))
        {
                jTdinero.setText("");           
        } else {
            try{
        Long a=Long.parseLong(jTdinero.getText());
            if(verificador==1)
        {
        salida.setText(String.valueOf(sahorr+a));
        } 
            if(verificador==2)
        {
        salida.setText(String.valueOf(scorr+a));
        }
        }
        catch(Exception err)
        {
            salida.setText("<Desconocido>");
        }
        }
        
    }//GEN-LAST:event_jTdineroMouseClicked

    private void jTdineroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdineroKeyReleased
                
        try{
        Long a=Long.parseLong(jTdinero.getText());
            if(verificador==1)
        {
        salida.setText(String.valueOf(sahorr+a));
        } 
            if(verificador==2)
        {
        salida.setText(String.valueOf(scorr+a));
        }
        }
        catch(Exception err)
        {
            salida.setText("<Desconocido>");
        }
        
    }//GEN-LAST:event_jTdineroKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBvolver;
    private javax.swing.JCheckBox jCahorro;
    private javax.swing.JCheckBox jCcorriente;
    private javax.swing.JLabel jLNom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JLabel jLsaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTdinero;
    private javax.swing.JLabel salida;
    // End of variables declaration//GEN-END:variables
}
